// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwysxjmaaimmwbvgffpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eXN4am1hYWltbXdidmdmZnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTYxOTUsImV4cCI6MjA2NDE5MjE5NX0.GJiDS_5saT0b9zHdYDMWhPQizHbu1WbQCRRZ1JfWRAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);